---
abstract: 'Provide CPAN metadata for cpanminus clients'
author:
  - 'Squeeks <squeek@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CPAN-MetaDB
no_index:
  directory:
    - t
    - inc
requires:
  IO::Uncompress::Gunzip: 0
  JSON: 0
  LWP::UserAgent: 0
  Plack: 0.99
  Test::More: 0
  YAML: 0
version: 0.03
